### ISSUE TITLE
Curl SSL error

### ISSUE THREAD

**Issue by WoutervanderLoopNL** [mattiabasone/MCAuth#10]
Hello. 

i get an Error with the SSL:

`cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

how do i solve this?

thanks so far, great API

**Comment by WoutervanderLoopNL** [comment]
ive temprary solved it by adding:
`'verify' => false` 
to 
`
    public function __construct() {
        $this->HttpClient = new GuzzleHttp\Client(
            [
                'headers' => [
                    'User-Agent' => self::USER_AGENT
                ],
				'verify' => false
            ]
        );
    }
` 
in MojangClient.php

but can you please make an function for it? like 
`$MCAuth->checkSSL = false;` 

Have an  nice day.

**Comment by mattiabasone** [comment]
Probably you haven't configured the curl.cainfo directive in the php.ini.
Take a look [here](https://docs.bolt.cm/3.4/howto/curl-ca-certificates)
