### ISSUE TITLE
Invalid Session

### ISSUE THREAD

**Issue by moose51789** [mattiabasone/MCAuth#5]
Love this, using it as authentication on my website but if someone logs in on the website while client is open they get invalid session from then on till they log out and back in.  Is there anyway around this or just how it is due to the way mojang has it setup?

**Comment by mattiabasone** [comment]
Hi, unfortunately I can't do anything for this 'issue'. Using the /authenticate endpoint of the Mojang API will overwrite any existing "accessToken" created.
I can suggest you to create a "session cookie" or a simple authentication system with a validation of the Minecraft account, only one time (for instance you will set premium = true in your database).
