### ISSUE TITLE
what is the const token for?

### ISSUE THREAD

**Issue by z1haze** [mattiabasone/MCAuth#6]
Hello, I'm just trying to use your script here to do some authentication with mojang, but im just wondering where does "const CLIENT_TOKEN  = '808772fc24bc4d92ba2dc48bfecb375f';           // Client token for authentication" come from? I see you get a token in an array back from mojang, but is that something you have to have before you can make the connection?

**Comment by comniemeer** [comment]
You can run it once without the client token and Mojang will generate one for you which you can use to make requests in the future.
I think the reason for this is that you don't abuse their service and authenticate you with the token so Mojang knows who makes how many requests.

**Comment by z1haze** [comment]
So the token that I replace is the token returned in my username array after first run?

**Comment by comniemeer** [comment]
Umm should be..






On Tue, May 5, 2015 at 4:48 PM -0700, "z1haze" <notifications@github.com> wrote:
So the token that I replace is the token returned in my username array after first run?

Sent from my iPhone, sorry for the typos.

> On May 5, 2015, at 7:20 PM, Martin Frühauf <notifications@github.com> wrote:
>
> You can run it once without the client token and Mojang will generate one for you which you can use to make requests in the future.
> I think the reason for this is that you don't abuse their service and authenticate you with the token so Mojang knows who makes how many requests.
>
> —
> Reply to this email directly or view it on GitHub.
>


---

**Comment by mattiabasone** [comment]
Hi,

The "clientToken" is an identifier of the client (for instance my website) that makes requests to the Mojang servers.
As reported by the wiki (http://wiki.vg/Authentication#Payload):
"The clientToken should be a randomly generated identifier and must be identical for each request. In case it is omitted the server will generate a random token based on Java's UUID.toString() which should then be stored by the client."

You can generate an unique ID here https://www.guidgenerator.com/online-guid-generator.aspx, at the moment MCAuth doesn't return the clientToken in the user array after the authentication.
