### ISSUE TITLE
Haspaid no longer exists.

### ISSUE THREAD

**Issue by ghost** [mattiabasone/MCAuth#7]
Haspaid.jsp now points to a 404.

**Comment by ReduxRedstone** [comment]
Can be fixed by using https://api.mojang.com/profiles/minecraft and checking for the "demo" flag. I have made my own auth script using this found here https://github.com/ReduxRedstone/minecraftAUTH-PHP

**Comment by ghost** [comment]
Ah, nice. Thanks for the info.
