### ISSUE TITLE
I know this is old, but I need help with it.

### ISSUE THREAD

**Issue by moderatorman** [mattiabasone/MCAuth#9]
I keep getting this error about SSL when I try and login.
`SSL certificate problem: unable to get local issuer certificate`

I turned off https redirects on my website, and it gave me the same error.

Again, I know this is old, but I would really appreciate it if I could get help with this issue.

**Comment by mattiabasone** [comment]
Check this issue [http://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate](http://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate)

You can get an updated cacert.pem [HERE](https://curl.haxx.se/ca/cacert.pem)

I've also tried to use MCAuth authentication on my server ([tester](http://minepic.org/MCAuth/)) and it works

**Comment by moderatorman** [comment]
Thanks, it's working now!

**Comment by mattiabasone** [comment]
Nice :)
